version: "3"
networks:
  proxy:
    external:
      name: dm_full_app

services:
  test_runner:
    build: .
    networks:
      - proxy
    image: pytest_runner
    container_name: pytest_runner_works
    volumes:
      - .:/smarts/

