version: "3"
networks:
  dm-full-app:
    external: true

services:
  test_runner:
    build: .
    networks:
      - dm-full-app
    image: pytest_runner
    container_name: pytest_runner_works
    volumes:
      - .:/smarts/

