service:
#  dm_api_account: http://localhost:5051
  dm_api_account: http://dm-api:5051

mailhog:
#  host: http://localhost:5025
  host: http://dm-mailhog:5025

test_user:
  user_name: test_user_4
  user_password: test_user_4

database:
  postgresql:
#    host: localhost
    host: dm-pg
    dbname: dm3.5
    user: postgres
    password: admin
    port: 5432
